=== alowu/EPAMFourthTask/src/main/resources/gems.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/gems"
        xmlns:tns="http://www.example.com/gems"
        elementFormDefault="qualified">

    <element name="gems">
        <complexType>
            <sequence>
                <element ref="tns:gem" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Gems">
        <sequence>
            <element name="name" type="string"/>
            <element name="visual" type="tns:GemsVisualParameters"/>
            <element name="value" type="positiveInteger"/>
        </sequence>
        <attribute name="id" use="required">
            <simpleType>
                <restriction base="ID">
                    <pattern value="[sp]\d{1,2}"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="amount" use="optional" default="0">
            <simpleType>
                <restriction base="positiveInteger">
                    <pattern value="\d{1,3}"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <complexType name="Natural">
        <complexContent>
            <extension base="tns:Gems">
                <sequence>
                    <element name="origin" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Precious">
        <complexContent>
            <extension base="tns:Natural">
                <sequence>
                    <element name="preciousness" fixed="precious"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Semiprecious">
        <complexContent>
            <extension base="tns:Natural">
                <sequence>
                    <element name="preciousness" fixed="semiprecious"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="GemsVisualParameters">
        <sequence>
            <element name="color" type="tns:EColor"/>
            <element name="transparency">
                <simpleType>
                    <restriction base="integer">
                        <minInclusive value="0"/>
                        <maxInclusive value="100"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="edges">
                <simpleType>
                    <restriction base="integer">
                        <minInclusive value="4"/>
                        <maxInclusive value="15"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>

    <simpleType name="EColor">
        <restriction base="string">
            <enumeration value="red"/>
            <enumeration value="green"/>
            <enumeration value="blue"/>
            <enumeration value="white"/>
        </restriction>
    </simpleType>

    <element name="gem" type="tns:Gems" abstract="true"/>
    <element name="precious" type="tns:Precious" substitutionGroup="tns:natural"/>
    <element name="semiprecious" type="tns:Semiprecious" substitutionGroup="tns:natural"/>
    <element name="natural" type="tns:Natural" substitutionGroup="tns:gem"/>

</schema>

=== alowu/EPAMFourthTask/src/test/java/com/epam/task/fourth/data/gems.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.example.com/gems"
      xsi:schemaLocation="http://www.example.com/gems gems.xsd">

    <precious id="p01">
        <name>diamond</name>
        <color>white</color>
        <value>150</value>
        <transparency>80</transparency>
        <edges>10</edges>
    </precious>
    <precious id="p02" amount="5">
        <name>ruby</name>
        <color>red</color>
        <value>100</value>
        <transparency>100</transparency>
        <edges>15</edges>
    </precious>
    <semiprecious id="s01">
        <name>apatite</name>
        <color>blue</color>
        <value>70</value>
        <transparency>70</transparency>
    </semiprecious>
    <semiprecious id="s02" amount="10">
        <name>prehnite</name>
        <color>green</color>
        <value>200</value>
        <transparency>50</transparency>
    </semiprecious>
</gems>

=== alowu/EPAMFourthTask/src/main/resources/gems.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.example.com/gems"
      xsi:schemaLocation="http://www.example.com/gems gems.xsd">

    <precious id="p01">
        <name>diamond</name>
        <visual>
            <color>white</color>
            <transparency>80</transparency>
            <edges>10</edges>
        </visual>
        <value>150</value>
        <origin>oregon</origin>
        <preciousness>precious</preciousness>
    </precious>
    <precious id="p02" amount="5">
        <name>ruby</name>
        <visual>
            <color>red</color>
            <transparency>100</transparency>
            <edges>15</edges>
        </visual>
        <value>100</value>
        <origin>siberia</origin>
        <preciousness>precious</preciousness>
    </precious>
    <semiprecious id="s01">
        <name>apatite</name>
        <visual>
            <color>blue</color>
            <transparency>70</transparency>
            <edges>15</edges>
        </visual>
        <value>70</value>
        <origin>germany</origin>
        <preciousness>semiprecious</preciousness>
    </semiprecious>
    <semiprecious id="s02" amount="10">
        <name>prehnite</name>
        <visual>
            <color>green</color>
            <transparency>50</transparency>
            <edges>7</edges>
        </visual>
        <value>200</value>
        <origin>africa</origin>
        <preciousness>semiprecious</preciousness>
    </semiprecious>
</gems>
